### ISSUE TITLE
Update code to match new 2015 data & specify repo on recode.r

### ISSUE THREAD

**Issue by MarioDiar** [diegovalle/download-maps12#1]
I was having some trouble when downloading the data, because the files downloaded from INEGI have different names now.

Also, I was having trouble when R was trying to install the packages and I solved it by especifying a repo in install.packages(new.packages, repos = "http://cran.us.r-project.org")

I can send a pull request if you want.

Saludos!

**Comment by diegovalle** [comment]
Thanks for the report. The files have been updated to reflect the latest download locations.

The proper place to specify a repo is in your .Rprofile

**Comment by MarioDiar** [comment]
Nice, no problem!
